# Generated by Django 5.0.6 on 2024-07-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_post_alter_user_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='father_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
