# Generated by Django 5.0.6 on 2024-07-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='end_subs',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subs',
            field=models.BooleanField(default=False),
        ),
    ]
