# Generated by Django 5.0.6 on 2024-07-08 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_user_is_director'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='user_id',
            new_name='user',
        ),
    ]
